# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

volumes:
  orderer0.${NETWORK}.com:
  orderer1.${NETWORK}.com:
  orderer2.${NETWORK}.com:

networks:
  ${NETWORK}:    
       name: ${NETWORK}
    

services:

  orderer0.${NETWORK}.com:
    container_name: orderer0.${NETWORK}.com
    image: hyperledger/fabric-orderer:2.5.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${ORDERER0LIS}
      - ORDERER_GENERAL_LOCALMSPID=${ORGNAMEFC}MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/${ORGNAME}/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/${ORGNAME}/users/Admin@${ORGNAME}.${NETWORK}.com/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${ORDERER0ADM}
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.${NETWORK}.com:${ORDERER0ADMOP}
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: ${ORGNAME}
    volumes:
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/${ORGNAME}s/orderer0.${NETWORK}.com/msp:/var/hyperledger/${ORGNAME}/msp
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/${ORGNAME}s/orderer0.${NETWORK}.com/tls/:/var/hyperledger/${ORGNAME}/tls
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/users/:/var/hyperledger/${ORGNAME}/users
        - orderer0.${NETWORK}.com:/var/hyperledger/production/${ORGNAME}
    ports:
      - ${ORDERER0LIS}:${ORDERER0LIS}
      - ${ORDERER0ADM}:${ORDERER0ADM}
      - ${ORDERER0ADMOP}:${ORDERER0ADMOP}
    networks:
      - ${NETWORK}
      
  orderer1.${NETWORK}.com:
    container_name: orderer1.${NETWORK}.com
    image: hyperledger/fabric-${ORGNAME}:2.5.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${ORDERER1LIS}
      - ORDERER_GENERAL_LOCALMSPID=${ORGNAMEFC}MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/${ORGNAME}/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/${ORGNAME}/users/Admin@${ORGNAME}.${NETWORK}.com/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${ORDERER1ADM}
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.${NETWORK}.com:${ORDERER1ADMOP}
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: ${ORGNAME}
    volumes:
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/${ORGNAME}s/orderer1.${NETWORK}.com/msp:/var/hyperledger/${ORGNAME}/msp
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/${ORGNAME}s/orderer1.${NETWORK}.com/tls/:/var/hyperledger/${ORGNAME}/tls
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/users/:/var/hyperledger/${ORGNAME}/users
        - orderer1.${NETWORK}.com:/var/hyperledger/production/${ORGNAME}
    ports:
      - ${ORDERER1LIS}:${ORDERER1LIS}
      - ${ORDERER1ADM}:${ORDERER1ADM}
      - ${ORDERER1ADMOP}:${ORDERER1ADMOP}
    networks:
      - ${NETWORK}
    
      
  orderer2.${NETWORK}.com:
    container_name: orderer2.${NETWORK}.com
    image: hyperledger/fabric-orderer:2.5.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${ORDERER2LIS}
      - ORDERER_GENERAL_LOCALMSPID=${ORGNAMEFC}MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/${ORGNAME}/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/${ORGNAME}/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/${ORGNAME}/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/${ORGNAME}/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/${ORGNAME}/users/Admin@${ORGNAME}.${NETWORK}.com/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${ORDERER2ADM}
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.${NETWORK}.com:${ORDERER2ADMOP}
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: ${ORGNAME}
    volumes:
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/${ORGNAME}s/orderer2.${NETWORK}.com/msp:/var/hyperledger/${ORGNAME}/msp
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/${ORGNAME}s/orderer2.${NETWORK}.com/tls/:/var/hyperledger/${ORGNAME}/tls
        - ../../../organizations/${ORGNAME}Organizations/${ORGNAME}.${NETWORK}.com/users/:/var/hyperledger/${ORGNAME}/users
        - orderer2.${NETWORK}.com:/var/hyperledger/production/${ORGNAME}
    ports:
      - ${ORDERER2LIS}:${ORDERER2LIS}
      - ${ORDERER2ADM}:${ORDERER2ADM}
      - ${ORDERER2ADMOP}:${ORDERER2ADMOP}
    networks:
      - ${NETWORK}
    
