# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


#Here remember we are using some setting of the fabric 2.3.2 version. In latest version compose files there is no core vm endpoint and a volume mapping present in compose files of peers. 
#So during peer chaincode install it was throwing some errors related to docker unix. So i added the core vm endpoint and some one other env variable and one volume mapping and it solved that
#error. One solution is this and other solution is to use latest peer images. Maybe i am having old images and that is the reason it is throwing such errors.  
#- CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK} (name of the docker network)
#- /var/run/docker.sock:/host/var/run/docker.sock
#Adding these 3 variables solved the issues. Also latest image version doesnt requirwe 



version: '3'

volumes:
  peer0.${ORGNAME}.${NETWORK}.com:
  peer1.${ORGNAME}.${NETWORK}.com:

networks:
  ${NETWORK}:    
       name: ${NETWORK}


services:

  peer0.${ORGNAME}.${NETWORK}.com:
    container_name: peer0.${ORGNAME}.${NETWORK}.com
    image: hyperledger/fabric-peer:2.5.4
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}  
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.${ORGNAME}.${NETWORK}.com
      - CORE_PEER_ADDRESS=peer0.${ORGNAME}.${NETWORK}.com:${PEER0LIS}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER0LIS}
      - CORE_PEER_CHAINCODEADDRESS=peer0.${ORGNAME}.${NETWORK}.com:${PEER0CC}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${PEER0CC}
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.${ORGNAME}.${NETWORK}.com:${PEER0LIS}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.${ORGNAME}.${NETWORK}.com:${PEER0LIS}
      - CORE_PEER_LOCALMSPID=${ORGNAMEFC}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.${ORGNAME}.${NETWORK}.com:${PEER0OP}
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - /var/run/:/host/var/run/
        - ../../../organizations/peerOrganizations/${ORGNAME}.${NETWORK}.com/peers/peer0.${ORGNAME}.${NETWORK}.com:/etc/hyperledger/fabric
        - peer0.${ORGNAME}.${NETWORK}.com:/var/hyperledger/production
        - ../../../../config/core.yaml:/etc/hyperledger/peercfg/core.yaml
        - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - ${PEER0LIS}:${PEER0LIS}
      - ${PEER0OP}:${PEER0OP}
    networks:
       - ${NETWORK}
 
         
  peer1.${ORGNAME}.${NETWORK}.com:
    container_name: peer1.${ORGNAME}.${NETWORK}.com
    image: hyperledger/fabric-peer:2.5.4
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}  
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer1.${ORGNAME}.${NETWORK}.com
      - CORE_PEER_ADDRESS=peer1.${ORGNAME}.${NETWORK}.com:${PEER1LIS}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER1LIS}
      - CORE_PEER_CHAINCODEADDRESS=peer1.${ORGNAME}.${NETWORK}.com:${PEER1CC}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${PEER1CC}
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.${ORGNAME}.${NETWORK}.com:${PEER1LIS}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.${ORGNAME}.${NETWORK}.com:${PEER1LIS}
      - CORE_PEER_LOCALMSPID=${ORGNAMEFC}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer1.${ORGNAME}.${NETWORK}.com:${PEER1OP}
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - /var/run/:/host/var/run/
        - ../../../organizations/peerOrganizations/${ORGNAME}.${NETWORK}.com/peers/peer1.${ORGNAME}.${NETWORK}.com:/etc/hyperledger/fabric
        - peer1.${ORGNAME}.${NETWORK}.com:/var/hyperledger/production
        - ../../../../config/core.yaml:/etc/hyperledger/peercfg/core.yaml
        - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - ${PEER1LIS}:${PEER1LIS}
      - ${PEER1OP}:${PEER1OP}
    networks:
       - ${NETWORK}
      
      

  
